
dsearches.conf
[Detected Brute-Force Attack via SSH]
action.webhook.enable_allowlist = 0
alert.digest_mode = true
alert.expires = 24h
alert.suppress = true
alert.suppress.fields = 
alert.suppress.period = 5m
alert.track = true
alert_condition = search count>3
counttype = number of events
cron_schedule = * * * * *
dispatch.earliest_time = rt-2m
dispatch.latest_time = rt-0m
enableSched = 1
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = index="*" "Failed password"
action.list = 1
action.list.severity = 3
quantity = 5
relation = greater than
